# Release: https://github.com/iscander01/confidential-avs-example/releases/tag/v1.0.0
# Workflow URL: https://github.com/iscander01/confidential-avs-example/actions/runs/16167570562
# Commit: https://github.com/iscander01/confidential-avs-example/commit/a04d182ddc3c9cf06d703232af596c4ceff4b730
# Dockerfile Path: Execution_Service/Dockerfile
# Docker Compose Location: Execution_Service/docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/iscander01/confidential-avs-example@sha256:feb76dee60e809f003e3efbb43caca946f18b1124c6a963660303590df4bb919
    ports:
      - '3000:80'
